<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {useRouter} from 'vue-router'
import {useAuthStore} from '@/stores/auth'
import {useUnreadStore} from '@/stores/unread'
import AppIcon from '@/components/common/AppIcon.vue'
import type {UnreadConversation,UnreadMode} from '@shared/unread'
const props=defineProps<{mode:UnreadMode}>(),emit=defineEmits<{close:[]}>()
const unread=useUnreadStore(),auth=useAuthStore(),router=useRouter(),filter=ref<UnreadMode|'all'>(props.mode),busy=ref(false),error=ref('')
const rows=computed(()=>unread.snapshot.conversations.filter(c=>filter.value==='all'||c.mode===filter.value))
const panel=ref<HTMLElement>()
onMounted(()=>{panel.value?.focus();void unread.refresh()})
function trap(event:KeyboardEvent){if(event.key!=='Tab'||!panel.value)return;const nodes=[...panel.value.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel.value)){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}
async function clear(){const snapshot=JSON.parse(JSON.stringify(rows.value));busy.value=true;error.value='';try{await unread.read(snapshot)}catch(e){error.value=e instanceof Error?e.message:'同步失败'}finally{busy.value=false}}
async function open(c:UnreadConversation){const first=c.messages[0];if(!first)return
 if(c.mode==='chat'&&c.profile)await auth.selectProfile(c.profile)
 await router.push({path:c.mode==='bot'?`/conversations/${encodeURIComponent(c.id)}`:`/chat/${encodeURIComponent(c.id)}`,query:{...(c.profile?{profile:c.profile}:{}),...(first.taskId?{taskId:first.taskId}:{}),unread:first.id}});emit('close')
}
</script>
<template><Teleport to="body"><div class="unread-overlay" @click.self="emit('close')" @keydown.esc="emit('close')"><section ref="panel" @keydown="trap" class="unread-panel" role="dialog" aria-modal="true" aria-label="未读消息" tabindex="-1"><header><h2>未读消息</h2><button type="button" aria-label="关闭未读消息" @click="emit('close')"><AppIcon name="close" /></button></header><div class="unread-controls"><div class="unread-filters" aria-label="消息模式"><button v-for="item in ([['all','全部'],['bot','Bot'],['chat','聊天']] as const)" :key="item[0]" :aria-pressed="filter===item[0]" @click="filter=item[0]">{{ item[1] }}</button></div><button :disabled="busy||!rows.length" @click="clear">全部标已读</button></div><p v-if="error||unread.error" role="status">{{ error||unread.error }}</p><div class="unread-rows"><button v-for="row in rows" :key="`${row.mode}:${row.profile}:${row.id}`" class="unread-row" @click="open(row)"><AppIcon :name="row.mode==='bot'?'users':'chat'" :size="22"/><span><strong>{{ row.name }}</strong><small>{{ row.mode==='bot'?'Bot':'聊天' }}<template v-if="row.profile"> · {{ row.profile }}</template></small><p>{{ row.preview }}</p></span><b :aria-label="`${row.count} 条未读`">{{ row.count>99?'99+':row.count }}</b></button><p v-if="!rows.length" class="unread-empty">暂无未读消息</p></div><footer>只统计完整聊天回复和附件。进入会话并看到正文后标为已读。</footer></section></div></Teleport></template>
<style scoped>
.unread-overlay{position:fixed;inset:0;z-index:5000;background:rgba(0,0,0,.18);display:flex;justify-content:flex-start;padding:64px 24px 24px 280px}.unread-panel{width:440px;max-height:calc(100vh - 88px);display:flex;flex-direction:column;background:var(--surface,#fff);color:var(--text,#202020);border:1px solid var(--border,#e6e6e6);border-radius:16px;box-shadow:0 16px 60px #0002;overflow:hidden}.unread-panel header{display:flex;align-items:center;justify-content:space-between;padding:18px 20px}.unread-panel h2{font-size:18px;margin:0}.unread-panel button{color:inherit;border:0;background:transparent;cursor:pointer;font:inherit}.unread-panel header button{padding:8px}.unread-controls{display:flex;justify-content:space-between;gap:10px;padding:0 16px 12px;border-bottom:1px solid var(--border,#eee)}.unread-controls>button{font-size:13px}.unread-controls button:disabled{opacity:.4}.unread-filters{display:flex;gap:4px}.unread-filters button{padding:7px 13px;border-radius:8px}.unread-filters button[aria-pressed=true]{background:var(--accent-soft,#f0edfa);color:var(--accent,#796bcd)}.unread-rows{overflow:auto;flex:1}.unread-row{display:flex;width:100%;align-items:center;gap:12px;padding:16px 20px;text-align:left;border-bottom:1px solid var(--border,#eee)!important}.unread-row:hover{background:var(--surface-hover,#f7f7f7)}.unread-row span{flex:1;min-width:0}.unread-row strong{display:block;font-size:15px}.unread-row small{display:block;opacity:.55;margin-top:4px}.unread-row p{margin:6px 0 0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;opacity:.65}.unread-row b{font-size:12px;border-radius:12px;padding:3px 8px;background:var(--accent,#796bcd);color:white;white-space:nowrap}.unread-empty{padding:48px;text-align:center;opacity:.6}.unread-panel footer{font-size:12px;opacity:.55;padding:14px 20px;border-top:1px solid var(--border,#eee)}:global(.dark) .unread-panel{background:#222;color:#eee;border-color:#383838}:global(.dark) .unread-row:hover{background:#2e2e2e}@media(max-width:900px){.unread-overlay{padding-left:80px}}
</style>
